### ISSUE TITLE
Support SSL for heroku through socketcluster

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/WebJamSocket#13]
- [x] web-jam-back-dev working again on 
  - [x] slug size is too large, limit is 500 MB
     * [x] edit combined-front to remove audio files
     * [x] edit combined front to remove mission and pub pages
     * [x]  combined front, move fact sheet pdf to dropbox then update homepage link and webpackconfig
    *  [x]  web-jam-back uses a BUILD_BRANCH env var not NODE_ENV for building the dev branches (frontend, webjammusic, store)
     * [x] edit JaMmusic menu to remove mission and pub pages
- [x] websockets from web-jam-back-dev to webjamsocket-dev
sctransport.js:10 Mixed Content: The page at 'https://web-jam-back-dev.herokuapp.com/music/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://webjamsocket-dev.herokuapp.com/socketcluster/'. This request has been blocked; this endpoint must be available over WSS.
o @ sctransport.js:10
f @ sctransport.js:46
w.connect.w.open @ scclientsocket.js:286
w @ scclientsocket.js:161
create @ factory.js:108
e.exports.create @ index.js:10
setupSocketCluster @ connectToSC.js:4
value @ index.js:23
za @ react-dom.production.min.js:216
Ha @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ps @ react-dom.production.min.js:250
Cs @ react-dom.production.min.js:249
Ts @ react-dom.production.min.js:248
Es @ react-dom.production.min.js:245
Ja @ react-dom.production.min.js:243
enqueueSetState @ react-dom.production.min.js:130
x.setState @ react.production.min.js:13
r.handlePersistorState @ react.js:43
p @ redux.js:220
io @ persistStore.js:59
v @ persistReducer.js:54
(anonymous) @ persistReducer.js:79
Promise.then (async)
(anonymous) @ persistReducer.js:78
Promise.then (async)
(anonymous) @ persistReducer.js:74
p @ redux.js:212
(anonymous) @ index.js:11
persist @ persistStore.js:93
(anonymous) @ persistStore.js:97
a @ bootstrap:79
(anonymous) @ app.79d49cdcb5ae00c48cef.bundle.js:2
a @ bootstrap:79
n @ bootstrap:45
(anonymous) @ bootstrap:152
(anonymous) @ app.79d49cdcb5ae00c48cef.bundle.js:2
sctransport.js:10 Uncaught (in promise) DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at o (https://web-jam-back-dev.herokuapp.com/music/app.79d49cdcb5ae00c48cef.bundle.js:2:904840)
    at new f (https://web-jam-back-dev.herokuapp.com/music/app.79d49cdcb5ae00c48cef.bundle.js:2:905356)
    at w.connect.w.open (https://web-jam-back-dev.herokuapp.com/music/app.79d49cdcb5ae00c48cef.bundle.js:2:461086)
    at new w (https://web-jam-back-dev.herokuapp.com/music/app.79d49cdcb5ae00c48cef.bundle.js:2:458968)
    at Object.create (https://web-jam-back-dev.herokuapp.com/music/app.79d49cdcb5ae00c48cef.bundle.js:2:918333)
    at Object.e.exports.create (https://web-jam-back-dev.herokuapp.com/music/app.79d49cdcb5ae00c48cef.bundle.js:2:561358)
    at Object.setupSocketCluster (https://web-jam-back-dev.herokuapp.com/music/app.79d49cdcb5ae00c48cef.bundle.js:2:560936)
    at t.value (https://web-jam-back-dev.herokuapp.com/music/app.79d49cdcb5ae00c48cef.bundle.js:2:1136316)
    at za (https://web-jam-back-dev.herokuapp.com/music/app.79d49cdcb5ae00c48cef.bundle.js:2:660490)
    at Ha (https://web-jam-back-dev.herokuapp.com/music/app.79d49cdcb5ae00c48cef.bundle.js:2:663165)

**Comment by JoshuaVSherman** [comment]
@Unesdala i'm working on this issue cause there are other problems with Heroku with the websockets needing to support ssl
