### ISSUE TITLE
MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by GigabyteCrippler** [WebJamApps/WebJamSocket#53]
installed and run WebJamSocket , error showing up in terminal 

1)
Error: Cannot find module 'socketcluster/fsutil'
Require stack:
- /Users/user/Desktop/cloned work /WebJamSocket/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/user/Desktop/cloned work /WebJamSocket/server.js:16:16)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/user/Desktop/cloned work /WebJamSocket/server.js' ]
}
![Screen Shot 2020-02-06 at 1 17 08 PM](https://user-images.githubusercontent.com/45514949/73940493-78390400-48e3-11ea-9030-adb3df327c6c.png)

**Comment by JoshuaVSherman** [comment]
@GigabyteCrippler thank you, yes this is a known issue, and I do appologize that I had forgotton about it, please lock the versions as follows until I figure out how to make it work in the latest version:

for JaMmusic, you need  "socketcluster-client": "14.3.1",

for WebJamSocket you need "socketcluster": "14.4.2",

**Comment by JoshuaVSherman** [comment]
@GigabyteCrippler where you able to get it running? can I close this issue now?

**Comment by GigabyteCrippler** [comment]
Yes please
